### ISSUE TITLE
TypeError: list indices must be integers or slices, not float

### ISSUE THREAD

**Issue by ModMaamari** [olehermanse/pyMaze---Maze-Generator-and-Game#1]
Traceback (most recent call last):
  File "main.py", line 437, in <module>
    generate()
  File "main.py", line 254, in generate
    rand[i] = seed * numbers[n] + i
TypeError: list indices must be integers or slices, not float

**Comment by olehermanse** [comment]
This project was written in python 2, a few years ago. I've fixed this error, but please beware that there might be other problems.
